"""Core package - Modules cœur d'EduSync AD."""

from edusync_ad.core.ad import (
    ADConnection,
    AsyncADConnection,
    ConnectResult,
    ConnectionState,
    Job,
    JobSignals,
    JobStatus,
    default_connection_factory,
    is_builtin_group_dn,
    ADError,
    ADAuthError,
    ADUnreachableError,
    ADInsufficientRightsError,
    ADCertificateError,
    # Cache (T2)
    ADCache,
    CacheStats,
    create_ad_cache,
)

from edusync_ad.plugins import (
    IModule,
    ModuleMetadata,
    PluginManager,
    ModuleLoadError,
    get_plugin_manager,
    reset_plugin_manager,
)

from edusync_ad.core.audit import AuditLog, new_session_id
from edusync_ad.core.config import AppConfig, load_config, save_config
from edusync_ad.core.csv_io import (
    CsvPreview,
    EXPECTED_COLUMNS,
    REQUIRED_COLUMNS,
    export_created_accounts,
    export_failed_rows,
    load_preview,
    load_rows,
)
from edusync_ad.core.identifiers import (
    CAMEL_PRESETS,
    PRESETS,
    IdentifierEngine,
    apply_prenom_compose_rule,
    clean_token,
    render_template,
)
from edusync_ad.core.models import (
    AccountType,
    GeneratedUser,
    MigrationRow,
    PasswordPolicy,
    RawUserRow,
)
from edusync_ad.core.password_vault import PasswordVault
from edusync_ad.core.passwords import (
    generate_password,
    generate_passwords_for_batch,
    PasswordPolicy,  # type: ignore[attr-defined]
)
from edusync_ad.core.crypto import (
    decrypt_str as decrypt,
    encrypt_str as encrypt,
    get_or_create_key,
    load_remembered_connection,
    save_remembered_connection,
    clear_remembered_connection,
)
from edusync_ad.core.multisite import (
    DomainProfile,
    MultisiteError,
    ensure_sites,
    find_profile,
    import_legacy_connection,
    load_sites,
    new_profile,
    profile_for_domain,
    save_sites,
    sites_path,
    unique_site_id,
)
from edusync_ad.core.updater import CURRENT_VERSION, check_for_update
from edusync_ad.core.export import build_export_row, export_users_csv, generate_labels_pdf
from edusync_ad.core.photos import (
    PhotoInfo,
    PhotoError,
    process_photo,
    process_photo_from_path,
    PhotoMapping,
    map_photos_convention,
    map_photos_from_csv,
    create_photo_preview_pixmap,
    photo_to_qicon,
)
from edusync_ad.core.profiles import (
    ProfileType,
    ProfileConfig,
    ProfileTemplate,
    ProfileManager,
    load_all_profile_configs,
    save_all_profile_configs,
)
from edusync_ad.core.homedirs import (
    HomeDirConfig,
    HomeDirManager,
    HomeDirPlan,
    load_home_dir_config,
    save_home_dir_config,
)
from edusync_ad.core.quotas import (
    QuotaSettings,
    QuotaPlan,
    QuotaManager,
    load_all_quota_configs,
    save_all_quota_configs,
)
from edusync_ad.core.logon_hours import (
    DISPLAY_DAYS,
    Grid,
    LogonHoursManager,
    LogonHoursPreset,
    current_utc_offset_hours,
    decode_logon_hours,
    encode_logon_hours,
    grid_summary,
    is_empty,
    is_unrestricted,
    new_grid,
)
from edusync_ad.core.logon_scripts import (
    SCRIPT_VARIABLES,
    LogonScript,
    LogonScriptManager,
    LogonScriptTemplate,
    ScriptPlan,
    build_context,
    deploy_scripts,
    load_logon_scripts,
    netlogon_path,
    render_script,
    save_logon_scripts,
    unknown_variables,
)
from edusync_ad.core.class_spaces import (
    ClassSpaceConfig,
    ClassSpaceManager,
    ClassSpacePlan,
    classify_member,
    creation_script,
    load_class_space_config,
    load_class_space_state,
    mark_synchronized,
    notify_group_created,
    plan_sync,
    save_class_space_config,
    sync_script,
)
from edusync_ad.core.graph import (
    GraphClient,
    GraphConfig,
    GraphError,
    load_m365_config,
    save_m365_config,
)
from edusync_ad.core.m365 import (
    DEFAULT_LICENSE,
    EDUCATION_LICENSES,
    GROUP_KINDS,
    CloudUserPlan,
    GroupPlan,
    M365Manager,
    SyncResult,
    build_group_plans,
    build_photo_mapping,
    build_user_plans,
    cloud_password_policy,
    hybrid_checklist,
    hybrid_checklist_markdown,
    mail_nickname,
    split_display_name,
)
from edusync_ad.core.exchange import (
    ALIAS_PATTERNS,
    MODES,
    AliasResult,
    ExchangeConfig,
    ExchangeManager,
    MailboxPlan,
    address_report_csv,
    build_group_address_plans,
    build_mailbox_plans,
    email_policy_script,
    load_exchange_config,
    normalize_local_part,
    onprem_script,
    online_script,
    save_exchange_config,
    warning_quota,
)
from edusync_ad.core.rds import (
    PROFILE_MODES,
    CollectionPlan,
    RDSConfig,
    RemoteAppPlan,
    build_collection_plan,
    collection_script,
    fslogix_script,
    load_rds_config,
    load_rds_plans,
    make_alias,
    normalize_group_ref,
    remoteapp_script,
    save_rds_config,
    save_rds_plans,
    split_multi,
    validate_collection,
    validate_remoteapp,
)
from edusync_ad.core.advanced_io import (
    DEFAULT_EXPORT_ATTRIBUTES,
    DEFAULT_HTML_TEMPLATE,
    LDAP_SOURCE_MODES,
    AdvancedIOConfig,
    LDAPSource,
    build_source_query,
    export_entries_csv,
    export_ldif,
    export_vcards,
    find_placeholders,
    gep_to_edusync_csv,
    import_from_ad,
    load_adv_io_config,
    merge_html,
    parse_gep_csv,
    render_template as render_html_template,
    run_external_tool,
    safe_filename,
    save_adv_io_config,
    suggest_gep_mapping,
    validate_ldap_filter,
    vcard_for,
)
from edusync_ad.core.templates import (
    GROUP_SCOPES,
    GROUP_TYPE_VALUES,
    TEMPLATE_KINDS,
    GroupAction,
    GroupSpec,
    GroupTemplate,
    InstantiationResult,
    builtin_templates,
    duplicate_template,
    export_template,
    export_template_xml,
    group_sam,
    import_template,
    import_template_xml,
    instantiate,
    load_templates,
    render_pattern,
    save_templates,
    unique_template_id,
    validate_values,
)
# M24 — Étiquettes & trombinoscopes : les noms qui chevauchent le module M23
# sont importés sous un alias explicite (pas de doublon dans __all__).
from edusync_ad.core.label_studio import (
    ALIGNMENTS,
    ELEMENT_KINDS,
    FONTS,
    SHEETS,
    LabelElement,
    LabelTemplate,
    MailConfig,
    MailError,
    SheetSpec,
    builtin_templates as builtin_label_templates,
    duplicate_template as duplicate_label_template,
    export_template as export_label_template,
    generate_trombinoscope_pdf,
    import_template as import_label_template,
    load_mail_config,
    load_templates as load_label_templates,
    render_labels_pdf,
    save_mail_config,
    save_templates as save_label_templates,
    send_label_email,
    unique_template_id as unique_label_template_id,
)

__all__ = [
    # AD
    "ADConnection",
    "AsyncADConnection",
    "ConnectResult",
    "ConnectionState",
    "Job",
    "JobSignals",
    "JobStatus",
    "default_connection_factory",
    "is_builtin_group_dn",
    "ADError",
    "ADAuthError",
    "ADUnreachableError",
    "ADInsufficientRightsError",
    "ADCertificateError",
    # Cache (T2)
    "ADCache",
    "CacheStats",
    "create_ad_cache",
    # Plugins (T1)
    "IModule",
    "ModuleMetadata",
    "PluginManager",
    "ModuleLoadError",
    "get_plugin_manager",
    "reset_plugin_manager",
    # Audit
    "AuditLog",
    "new_session_id",
    # Config
    "AppConfig",
    "load_config",
    "save_config",
    # CSV
    "CsvPreview",
    "EXPECTED_COLUMNS",
    "REQUIRED_COLUMNS",
    "export_created_accounts",
    "export_failed_rows",
    "load_preview",
    "load_rows",
    # Identifiers
    "CAMEL_PRESETS",
    "PRESETS",
    "IdentifierEngine",
    "apply_prenom_compose_rule",
    "clean_token",
    "render_template",
    # Models
    "AccountType",
    "GeneratedUser",
    "MigrationRow",
    "PasswordPolicy",
    "RawUserRow",
    # Password vault
    "PasswordVault",
    # Passwords
    "generate_password",
    "generate_passwords_for_batch",
    # Crypto
    "decrypt",
    "encrypt",
    "get_or_create_key",
    "load_remembered_connection",
    "save_remembered_connection",
    "clear_remembered_connection",
    # Updater
    "CURRENT_VERSION",
    "check_for_update",
    # Export
    "build_export_row",
    "export_users_csv",
    "generate_labels_pdf",
    # Photos (M12)
    "PhotoInfo",
    "PhotoError",
    "process_photo",
    "process_photo_from_path",
    "PhotoMapping",
    "map_photos_convention",
    "map_photos_from_csv",
    "create_photo_preview_pixmap",
    "photo_to_qicon",
    # Profils (M13)
    "ProfileType",
    "ProfileConfig",
    "ProfileTemplate",
    "ProfileManager",
    "load_all_profile_configs",
    "save_all_profile_configs",
    # Dossiers personnels (M17)
    "HomeDirConfig",
    "HomeDirManager",
    "HomeDirPlan",
    "load_home_dir_config",
    "save_home_dir_config",
    # Quotas FSRM (M14)
    "QuotaSettings",
    "QuotaPlan",
    "QuotaManager",
    "load_all_quota_configs",
    "save_all_quota_configs",
    # Heures de connexion (M16)
    "DISPLAY_DAYS",
    "Grid",
    "LogonHoursManager",
    "LogonHoursPreset",
    "current_utc_offset_hours",
    "decode_logon_hours",
    "encode_logon_hours",
    "grid_summary",
    "is_empty",
    "is_unrestricted",
    "new_grid",
    # Scripts logon/logoff (M15)
    "SCRIPT_VARIABLES",
    "LogonScript",
    "LogonScriptManager",
    "LogonScriptTemplate",
    "ScriptPlan",
    "build_context",
    "deploy_scripts",
    "load_logon_scripts",
    "netlogon_path",
    "render_script",
    "save_logon_scripts",
    "unknown_variables",
    # Espaces partagés par classe (M18)
    "ClassSpaceConfig",
    "ClassSpaceManager",
    "ClassSpacePlan",
    "classify_member",
    "creation_script",
    "load_class_space_config",
    "load_class_space_state",
    "mark_synchronized",
    "notify_group_created",
    "plan_sync",
    "save_class_space_config",
    "sync_script",
    # Office 365 / Entra ID (M19)
    "GraphClient",
    "GraphConfig",
    "GraphError",
    "load_m365_config",
    "save_m365_config",
    "DEFAULT_LICENSE",
    "EDUCATION_LICENSES",
    "GROUP_KINDS",
    "CloudUserPlan",
    "GroupPlan",
    "M365Manager",
    "SyncResult",
    "build_group_plans",
    "build_photo_mapping",
    "build_user_plans",
    "cloud_password_policy",
    "hybrid_checklist",
    "hybrid_checklist_markdown",
    "mail_nickname",
    "split_display_name",
    # Exchange (M20)
    "ALIAS_PATTERNS",
    "MODES",
    "AliasResult",
    "ExchangeConfig",
    "ExchangeManager",
    "MailboxPlan",
    "address_report_csv",
    "build_group_address_plans",
    "build_mailbox_plans",
    "email_policy_script",
    "load_exchange_config",
    "normalize_local_part",
    "onprem_script",
    "online_script",
    "save_exchange_config",
    "warning_quota",
    # RDS (M21)
    "PROFILE_MODES",
    "CollectionPlan",
    "RDSConfig",
    "RemoteAppPlan",
    "build_collection_plan",
    "collection_script",
    "fslogix_script",
    "load_rds_config",
    "load_rds_plans",
    "make_alias",
    "normalize_group_ref",
    "remoteapp_script",
    "save_rds_config",
    "save_rds_plans",
    "split_multi",
    "validate_collection",
    "validate_remoteapp",
    # Import/Export avancés (M22)
    "DEFAULT_EXPORT_ATTRIBUTES",
    "DEFAULT_HTML_TEMPLATE",
    "LDAP_SOURCE_MODES",
    "AdvancedIOConfig",
    "LDAPSource",
    "build_source_query",
    "export_entries_csv",
    "export_ldif",
    "export_vcards",
    "find_placeholders",
    "gep_to_edusync_csv",
    "import_from_ad",
    "load_adv_io_config",
    "merge_html",
    "parse_gep_csv",
    "render_html_template",
    "run_external_tool",
    "safe_filename",
    "save_adv_io_config",
    "suggest_gep_mapping",
    "validate_ldap_filter",
    "vcard_for",
    # Modèles de groupes (M23)
    "GROUP_SCOPES",
    "GROUP_TYPE_VALUES",
    "TEMPLATE_KINDS",
    "GroupAction",
    "GroupSpec",
    "GroupTemplate",
    "InstantiationResult",
    "builtin_templates",
    "duplicate_template",
    "export_template",
    "export_template_xml",
    "group_sam",
    "import_template",
    "import_template_xml",
    "instantiate",
    "load_templates",
    "render_pattern",
    "save_templates",
    "unique_template_id",
    "validate_values",
    # M24 — Étiquettes & trombinoscopes
    "ALIGNMENTS",
    "ELEMENT_KINDS",
    "FONTS",
    "SHEETS",
    "LabelElement",
    "LabelTemplate",
    "MailConfig",
    "MailError",
    "SheetSpec",
    "builtin_label_templates",
    "duplicate_label_template",
    "export_label_template",
    "generate_trombinoscope_pdf",
    "import_label_template",
    "load_mail_config",
    "load_label_templates",
    "render_labels_pdf",
    "save_mail_config",
    "save_label_templates",
    "send_label_email",
    "unique_label_template_id",
    # M25 — Multisite / multi-domaine
    "DomainProfile",
    "MultisiteError",
    "ensure_sites",
    "find_profile",
    "import_legacy_connection",
    "load_sites",
    "new_profile",
    "profile_for_domain",
    "save_sites",
    "sites_path",
    "unique_site_id",
]
